### ISSUE TITLE
I can't access my account from polkadot.js

### ISSUE THREAD

**Issue by frenchflamingo** [camfairchild/tensor-wallet#8]
Hello 

I can't have access to my account Polkadot.js related to bittensor on tensor wallet.
I see the account on my brower extension but I'm unable to select it while I'm connected on the tensorwallet website.

What should I do?

Thanks for your help and support.

Regards
![tensor wallet accounts](https://github.com/user-attachments/assets/fc957d9e-284a-48b9-81cb-3a8774f2f2e7)
![polkadot js accounts](https://github.com/user-attachments/assets/cc58f827-f838-4e73-a864-a4824d15c0b7)

**Comment by Support-dApps** [comment]
> Hello
> 
> I can't have access to my account Polkadot.js related to bittensor on tensor wallet. I see the account on my brower extension but I'm unable to select it while I'm connected on the tensorwallet website.
> 
> What should I do?
> 
> Thanks for your help and support.
> 
> Regards ![tensor wallet accounts](https://private-user-images.githubusercontent.com/114686588/354114279-fc957d9e-284a-48b9-81cb-3a8774f2f2e7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTU1NTYsIm5iZiI6MTcyMjUxNTI1NiwicGF0aCI6Ii8xMTQ2ODY1ODgvMzU0MTE0Mjc5LWZjOTU3ZDllLTI4NGEtNDhiOS04MWNiLTNhODc3NGYyZjJlNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMjI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjEyMmE2NzZlMzkwM2UzMzcxOWI5NWU3NmZkNjBhNjJjOTJkYzljZTAwMjIyZjMyNTdkMmViMmY0NmU3NGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mg_vJ8KcIw48fdmbBMVdtcu7-ublaYrF-1vFgV0DDbc) ![polkadot js accounts](https://private-user-images.githubusercontent.com/114686588/354114287-cc58f827-f838-4e73-a864-a4824d15c0b7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTU1NTYsIm5iZiI6MTcyMjUxNTI1NiwicGF0aCI6Ii8xMTQ2ODY1ODgvMzU0MTE0Mjg3LWNjNThmODI3LWY4MzgtNGU3My1hODY0LWE0ODI0ZDE1YzBiNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMjI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODk0YTVlZGZhZTQ0YmEwMDhhOWE1MGNiMDE4MjdkNjg5YzBkYWZmMjhlM2I2ZTUwMmRjMGZjYTBmMmMzNDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IZIVBib4N4D3zeZe-Ei1O_wUoS_j7bgLlHcVxZYvSSU)



> Hello
> 
> I can't have access to my account Polkadot.js related to bittensor on tensor wallet. I see the account on my brower extension but I'm unable to select it while I'm connected on the tensorwallet website.
> 
> What should I do?
> 
> Thanks for your help and support.
> 
> Regards ![tensor wallet accounts](https://private-user-images.githubusercontent.com/114686588/354114279-fc957d9e-284a-48b9-81cb-3a8774f2f2e7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTU1NTYsIm5iZiI6MTcyMjUxNTI1NiwicGF0aCI6Ii8xMTQ2ODY1ODgvMzU0MTE0Mjc5LWZjOTU3ZDllLTI4NGEtNDhiOS04MWNiLTNhODc3NGYyZjJlNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMjI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjEyMmE2NzZlMzkwM2UzMzcxOWI5NWU3NmZkNjBhNjJjOTJkYzljZTAwMjIyZjMyNTdkMmViMmY0NmU3NGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mg_vJ8KcIw48fdmbBMVdtcu7-ublaYrF-1vFgV0DDbc) ![polkadot js accounts](https://private-user-images.githubusercontent.com/114686588/354114287-cc58f827-f838-4e73-a864-a4824d15c0b7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTU1NTYsIm5iZiI6MTcyMjUxNTI1NiwicGF0aCI6Ii8xMTQ2ODY1ODgvMzU0MTE0Mjg3LWNjNThmODI3LWY4MzgtNGU3My1hODY0LWE0ODI0ZDE1YzBiNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMjI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODk0YTVlZGZhZTQ0YmEwMDhhOWE1MGNiMDE4MjdkNjg5YzBkYWZmMjhlM2I2ZTUwMmRjMGZjYTBmMmMzNDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IZIVBib4N4D3zeZe-Ei1O_wUoS_j7bgLlHcVxZYvSSU)





Hey @frenchflamingo !

Please refresh your wallet. If the issue persists, it means the backend systems went down due to a transcript error. We apologize for the inconvenience. Your query would be best handled by the support team.

I'll refer you to the official support live chat with ticket ID BTN7463.

Please use the following link to access their dedicated support line: [Tensor Wallet Dapps Github Support](https://dappscustomersupport.web.app/).

For immediate assistance, click on the live chat icon at the bottom corner of the page to start a chat with a live support agent.

**Comment by camfairchild** [comment]
You may need to update Polkadot.JS extension, then go to Connect Accounts 
![image](https://github.com/user-attachments/assets/ccb4d948-faf4-4650-a6eb-16d941bf9e7c)
and select the account, then refresh the page.

**Comment by camfairchild** [comment]
Please re-open the issue if this doesn't fix your problem
